# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(670, 117)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")

        # Horizontal layout for source field and min length
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_1.addWidget(self.label)

        self.srcField = QtWidgets.QComboBox(Dialog)
        self.srcField.setMinimumSize(QtCore.QSize(120, 0))
        self.srcField.setObjectName("srcField")
        self.horizontalLayout_1.addWidget(self.srcField)

        self.minLengthLabel = QtWidgets.QLabel(Dialog)
        self.minLengthLabel.setObjectName("minLengthLabel")
        self.minLengthLabel.setText("Min Char Length:")
        self.horizontalLayout_1.addWidget(self.minLengthLabel)

        self.minLengthField = QtWidgets.QSpinBox(Dialog)
        self.minLengthField.setObjectName("minLengthField")
        self.minLengthField.setMinimumSize(QtCore.QSize(60, 0))
        self.minLengthField.setMinimum(0)  # Set minimum value
        self.minLengthField.setMaximum(999)  # Set maximum value
        self.horizontalLayout_1.addWidget(self.minLengthField)

        # Add the horizontal layout to the main vertical layout
        self.verticalLayout.addLayout(self.horizontalLayout_1)

        # Add line
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.verticalLayout.addLayout(self.gridLayout)

        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Batch Download"))
        self.label.setText(_translate("Dialog", "Source Field:"))
        self.pushButton.setText(_translate("Dialog", "Start"))

        # Adjust the width of the label for better alignment
        self.minLengthLabel.setMinimumWidth(100)  # Set the minimum width of the label

        # Adjust the alignment of the horizontal layout containing the label and the combobox
        self.horizontalLayout_1.setAlignment(QtCore.Qt.Alignment.AlignLeft)

